server:
  port: 8083

spring:
  data:
    redis:
      host: localhost
      port: 6379
    
  application:
    name: user-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 추적
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: '*'

  jwt:
    private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCUiEr5I6dUmZVxIfMUCrrIG/ei5I3rwpz9iSRLdU2PRJ8LNMwICkLc15qEqYAG5q7QLnoU36rn0Hv0+FqLvtk3af6fYNmUluPr5mG7zSmoHhMd9dPPNczc0vT+mac0zx9oeOyf5Kkm08e+IqhkqoizLzmhN97t8lpWRmQgZGv82Lp7IUIukA8Gv1/67gSNCj7Y7Eam+6dLv5IcJpYCB0EPiGvpLPSnC4iTfdCvd9peWJh67/z9Yr9i6V/FLzotDeDy7J/kzo0Hjn7EzKd5guweWtA7jbNOP9iEY/sYX6dHvisypIkr3NC+0LsZHmuR9PzUvqWJOZw3gV4D6zEBJ4G1AgMBAAECggEAFESw7mRmHg5DLUfzsqVwLYRbe3fywdwxrgs7z6w3JDi59z6CJQq5awdkx3uVw9tQuYnOEPEgkjeJ4rjNKkqlu4EURM1jg3o/qd4rMgRiDdXkx+7Ws2zlArEqy19OSM+Guqvdpkf+qRS3KgPytKHsu37TP2OvYQr0NteuLBln/v2i4XrUyCBX8C+3Yh6Ei7EPEpqn0FJqY1eEX780kfk2aprJNZQ7WWIFKs5RwEgYEDN9C3OUNLGGEGKOG95jDEnQKyhdigOho2BDFTchRx3xLhie9ox8Xcl8K5F16uwpkcU57dT6HNGv5PIHlEtq2d102V14Fwqe6ZVBEi8Opu1M9QKBgQDHYIqM+9lcHt5x7bFbXQj6xV7Qw8wnOPJHWBEbXr7v4ejDki9zEiVkPKDQHzTmH5UF8BnZH8CQkIY46tlYO1JnHsVPcRnQ/jN2/IWqsXwOjl5XZzXw+sLrsyxL8lE82Q4/D1B+ZMMNszFLDjMNBMW50y0hXH88tQVWJBBA2qOGhwKBgQC+tyawE0dtwmrcbEb5yqcLWYzgQudJLRyX7vLciGFpJKhzdSYvdyVyQ3hAlQSRl6ji3i1CDuCmtYPMssKxAOhvEPfN4Q0rXKF3GBu/meA2VGv3saK0JgjZUlSGZzwd8kHHd32btzgVssyfaLKLBx8YrHvOEl865DyT0ComdDUI4wKBgAUh2A8vAHZdmQ5HtxQJ/gwufnVTRPMRhTMO8knJE5MrNomqPqxwoCPHZ8BTvVHbKEPh3Vh4d8WA4uOeMAAUbteWtC+KUsbNdFewwmQVc4MQaR9I2dudKN1WXGKMF0lAsRwwcbr/LwIwRamP8QJ5x/kzlWrRbbkLU9rWzNBOkH0LAoGASkIqMDjxgQ1IapdGc5CyxjqSHegvAlEsZwRFUBVSSIxbgslEmwq7a+hVdGARrVbuDZgQ6z27v23B6fxYzm7aEhT7SBCu/glNXX/nng0ePklU2Ncz0Q1WOLhT7RlZURe5AR/HqtAGaHx8LD2p93RIaWUPt8dziQzBgZR2NQ7eb50CgYAYVgeegzeOGn5vMOas87VQfBqyxk0oLTuCYTK/pnvZqbgEUOOU9NKXima+T9cfYcnziJVN956hJ0NOCXA4OY4XjCsFhDM3aowSJEk8Ks7lkV0szHUzdj4HGF5g8deimiyGmvP+qbWTYYKiEd7cV+nhlcVHaXOUphcc70hWSHdxlQ==
    expire-time:
      access-token: 900000
      refresh-token: 2592000000
    
